---
title: "Ecology and Evolution PhD Program Beginner's R Workshop"
author: "David Wilkinson"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: Doi90/EcolEvol_R_Workshop
---

# Preamble

This is the course notes for the *Beginner's R Workshop* for the Ecology and Evolution PhD program joint venture of the School of BioSciences, School of Ecosystem and Forestry Science, and School of Geography. The goal of this workshop is to teach new PhD students how to use **R** for data analysis. **R** is a free, open-source programming language designed with statistical analysis in mind, and widely used throught many scientific disciplines. This workshop is designed to provide new PhD students in our three Schools with a strong foundation in **R**'s fundamentals to facilitate their own research projects.

This course will not assume any prior experience with **R**, but we recommend that attendees with no prior programming experience at all refer to the course material at [Introduction To Programming Concepts](https://nikkirubinstein.gitbooks.io/resguides-introductory-programming-concepts/content/content/welcome-to-coding.html) in advance. We will introduce these concepts during the workshop, but a basic understanding aforehand will help you get to grips with **R** faster. 

This material has been adapted with permission from Research Platforms Services's own [*Introductory R Workshop*](https://nikkirubinstein.gitbooks.io/resguides-introductory-r-workshop/content/) course material.

# Technical Requirements

All attendees will be required to **bring their own laptop and charger**. Tablets and/or Chromebooks (or similar) are not recommended. It can have a Windows, Mac, or Linux operating system, but you must have administrative priveleges.

Attendees are also asked to install both [**R**](https://www.r-project.org/) and [**RStudio**](https://www.rstudio.com/) in advance of the workshop. Both **R** and **RStudio** are updated regularly with both new features and bug fixes, so we require attendees to have **R** v3.4 or later, and **RStudio** v1.1.383 or later.